spring:
  application:
    name: AI-Code-Review

server:
  port: 8081

logging:
  level:
    root: info

config:
  ssh:
    key:
      url: id_rsa密钥文件地址
  mail:
    user:
      from: 发件人邮箱（一个）
      to: 发件人邮箱（可以配置多个，用英文逗号分割）
    authorization:
      code: 授权码
  ai:
    tongyi:
      api-key: 通义千问API-Key